import LeanKohaku

open LeanKohaku.Cli.Commands

namespace LeanKohaku.Cli

open LeanKohaku.Keystore.Tpm2Runtime

def pathExists (path : System.FilePath) : BaseIO Bool :=
  path.pathExists

def tpm2CreateStatusText : CreateStatus → String
  | .created => "created"
  | .alreadyExists => "already exists"
  | .invalidKeyName => "invalid key name"
  | .missingTpmDevice => "missing TPM device"
  | .missingTool tool => s!"missing required tool: {tool}"
  | .biometricVerificationFailed stderr =>
      s!"biometric verification failed\n\n{stderr}"
  | .policyRejected => "Sepolia R1 account policy rejected"
  | .commandFailed cmd stderr =>
      s!"command failed: {cmd}\n\n{stderr}"

def tpm2CreateReportText (report : CreateReport) : String :=
  "leanKohaku Sepolia TPM2 wallet creation\n\n\
   Requested wallet:\n\
     - chain: Sepolia (11155111)\n\
     - account: r1-smart dev account\n\
     - backend: local Linux TPM2\n\
     - curve: P-256/R1\n\
     - custody: local only; no online keystore\n\n\
   Result:\n\
     - status: " ++ tpm2CreateStatusText report.status ++ "\n\
     - key directory: " ++ report.keyDir.toString ++ "\n\
     - public key: " ++ report.publicKey.toString ++ "\n\
     - manifest: " ++ report.manifest.toString ++ "\n\n\
   Security boundary:\n\
     - created through local tpm2-tools only\n\
     - new key creation requires local fprintd biometric verification\n\
     - no seed or raw private key is generated by Lean\n\
     - TPM private blob remains wrapped for the local TPM\n\
     - biometric verification is a local gate, not yet a TPM policy session\n"

def signStatusText : SignStatus → String
  | .signed => "signed"
  | .invalidKeyName => "invalid key name"
  | .invalidDigest => "invalid digest: expected 32-byte hex"
  | .missingKey => "missing key"
  | .missingTpmDevice => "missing TPM device"
  | .missingTool tool => s!"missing required tool: {tool}"
  | .biometricVerificationFailed stderr =>
      s!"biometric verification failed\n\n{stderr}"
  | .commandFailed cmd stderr =>
      s!"command failed: {cmd}\n\n{stderr}"

def tpm2SignReportText (report : SignReport) : String :=
  let sigLine :=
    match report.signatureHex with
    | none => ""
    | some sig => "     - signature hex: " ++ sig ++ "\n"
  "leanKohaku Sepolia TPM2 signing\n\n\
   Requested signer:\n\
     - chain: Sepolia (11155111)\n\
     - key name: " ++ report.keyName ++ "\n\
     - backend: local Linux TPM2\n\n\
   Result:\n\
     - status: " ++ signStatusText report.status ++ "\n\
     - key directory: " ++ report.keyDir.toString ++ "\n\
     - digest file: " ++ report.digest.toString ++ "\n\
     - signature file: " ++ report.signature.toString ++ "\n" ++ sigLine ++
  "\n\
   Security boundary:\n\
     - signing requires local fprintd biometric verification\n\
     - digest and signature stay under the local .leankohaku state directory\n\
     - TPM private blob remains wrapped for the local TPM\n"

def formatKeyList : List String → String
  | [] => "No local Sepolia TPM2 keys found.\n"
  | names =>
      "Local Sepolia TPM2 keys:\n" ++
        String.join (names.map (fun name => "- " ++ name ++ "\n"))

def runSepoliaWalletCreate (keyName : String) : IO UInt32 := do
  let report ← createSepoliaR1Key { keyName := keyName }
  IO.println (tpm2CreateReportText report)
  return report.status.exitCode

def runSepoliaWalletList : IO UInt32 := do
  let names ← listSepoliaKeys
  IO.print (formatKeyList names)
  return 0

def runSepoliaWalletSign (keyName : String) (digestHex : String) : IO UInt32 := do
  let report ← signSepoliaDigest digestHex { keyName := keyName }
  IO.println (tpm2SignReportText report)
  return report.status.exitCode

end LeanKohaku.Cli

def main (args : List String) : IO UInt32 := do
  match parse args with
  | .help       => IO.println helpText; return 0
  | .version    => IO.println s!"leankohaku {LeanKohaku.version}"; return 0
  | .privacy    => IO.println privacyText; return 0
  | .lightclient => IO.println lightclientText; return 0
  | .keystore   => IO.println keystoreText; return 0
  | .accounts   => IO.println accountsText; return 0
  | .walletCreateSepolia keyName => LeanKohaku.Cli.runSepoliaWalletCreate keyName
  | .walletListSepolia => LeanKohaku.Cli.runSepoliaWalletList
  | .walletSignSepolia keyName digestHex => LeanKohaku.Cli.runSepoliaWalletSign keyName digestHex
  | .daemon     =>
      LeanKohaku.Daemon.Server.run LeanKohaku.Daemon.Server.defaultConfig
      return 0
  | .balance a  =>
      IO.println s!"balance {a}: (not yet implemented — needs daemon + RPC)"
      return 1
  | .send to amount =>
      IO.println s!"send {amount} → {to}: (not yet implemented — needs signer)"
      return 1
