#!/usr/bin/env bash
# Build the kohaku-bridge Node sidecar consumed by
# LeanKohaku.Privacy.Bridge. Mirrors script/setup_hacl.sh: pin upstream
# packages, install with --ignore-scripts to neutralize npm install-time
# code execution, and emit a small wrapper into .lake/build/bin/ so the
# daemon can exec `leankohaku-kohaku-bridge` without a global install.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BRIDGE_SRC="${ROOT}/bridge"
BRIDGE_DEST="${ROOT}/.lake/bridge"
HELPER_DIR="${ROOT}/.lake/build/bin"
WRAPPER="${HELPER_DIR}/leankohaku-kohaku-bridge"

missing=()
for tool in node npm; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    missing+=("$tool")
  fi
done

if [[ "${#missing[@]}" -ne 0 ]]; then
  echo "missing tools: ${missing[*]} (need node>=22, npm)" >&2
  echo "Ubuntu: sudo apt install nodejs npm" >&2
  echo "Arch:   sudo pacman -S nodejs npm" >&2
  exit 1
fi

NODE_MAJOR="$(node -e 'process.stdout.write(String(process.versions.node.split(".")[0]))')"
if (( NODE_MAJOR < 22 )); then
  echo "node ${NODE_MAJOR} too old; @kohaku-eth/* require node>=22" >&2
  exit 1
fi

mkdir -p "$BRIDGE_DEST" "$HELPER_DIR"

cp "$BRIDGE_SRC/package.json" "$BRIDGE_DEST/package.json"
cp "$BRIDGE_SRC/bridge.mjs" "$BRIDGE_DEST/bridge.mjs"
if [[ -f "$BRIDGE_SRC/package-lock.json" ]]; then
  cp "$BRIDGE_SRC/package-lock.json" "$BRIDGE_DEST/package-lock.json"
fi

pushd "$BRIDGE_DEST" >/dev/null
if [[ -f package-lock.json ]]; then
  npm ci --omit=dev --ignore-scripts
else
  echo "warning: bridge/package-lock.json missing; using 'npm install --ignore-scripts'." >&2
  echo "         commit bridge/package-lock.json before shipping for supply-chain pinning." >&2
  npm install --omit=dev --ignore-scripts --no-audit --no-fund
fi
popd >/dev/null

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by script/setup_railgun.sh — do not edit.
exec node "${BRIDGE_DEST}/bridge.mjs" "\$@"
EOF
chmod +x "$WRAPPER"

cat <<EOF
Kohaku bridge installed at:
  $BRIDGE_DEST

Wrapper installed at:
  $WRAPPER

Smoke test:
  $WRAPPER --rpc '{"jsonrpc":"2.0","method":"ping","id":1}'
EOF
