import LeanKohaku.Basic
import LeanKohaku.Daemon.Log
import LeanKohaku.Daemon.State
import LeanKohaku.Daemon.Uds
import LeanKohaku.Privacy.NetworkPolicy
import LeanKohaku.Privacy.Bridge
import LeanKohaku.RPC.Outbound
import LeanKohaku.RPC.Server
import LeanKohaku.Ethereum.Address
import LeanKohaku.Ethereum.Tx
import LeanKohaku.Keystore.Tpm2Runtime
import LeanKohaku.Wallet.Address
import LeanKohaku.Wallet.Bip44
import LeanKohaku.Wallet.EoaStore
import LeanKohaku.Wallet.Entropy
import LeanKohaku.Wallet.EOA
import LeanKohaku.Wallet.HDKey
import LeanKohaku.Wallet.Mnemonic

/-!
# Daemon server

Long-running process that exposes wallet operations over a local socket.
The daemon is the only component allowed to perform Ethereum node I/O, and
every attempted connection must pass `Privacy.NetworkPolicy`.
-/

namespace LeanKohaku.Daemon.Server

open LeanKohaku.Encoding.Json
open LeanKohaku.Keystore.Tpm2Runtime
open LeanKohaku.Privacy.NetworkPolicy
open LeanKohaku.RPC.Server

def defaultDerivationPath : String := "m/44'/60'/0'/0/0"

structure Config where
  socketPath : String
  chainId    : Nat
  policy     : Policy
  rpcEndpoint : LeanKohaku.RPC.Outbound.Endpoint

instance : Repr Config where
  reprPrec cfg _ :=
    "Config(socketPath := " ++ repr cfg.socketPath ++
      ", chainId := " ++ repr cfg.chainId ++
      ", policy := <function>)"

def defaultConfig : Config :=
  { socketPath := "/tmp/leankohaku.sock",
    chainId := 1,
    policy := strictDaemonPolicy,
    rpcEndpoint := LeanKohaku.RPC.Outbound.endpointFromUrl "http://127.0.0.1:8545" }

private def slotMetadataJson (state : LeanKohaku.Daemon.State.Shared)
    (record : LeanKohaku.Wallet.EoaStore.Record) : IO Json := do
  let unlocked ← LeanKohaku.Daemon.State.isUnlocked state record.name
  pure <| .obj #[
    ("name", .str record.name),
    ("address", .str record.address),
    ("derivationPath", .str record.derivationPath),
    ("locked", .bool (!unlocked)),
    ("createdAt", .num (Int.ofNat record.createdAt))
  ]

private def textResultJson (text : String) (exitCode : UInt32) : Json :=
  .obj #[
    ("text", .str text),
    ("exitCode", .num (Int.ofNat exitCode.toNat))
  ]

private def tpm2CreateStatusText : CreateStatus → String
  | .created => "created"
  | .alreadyExists => "already exists"
  | .invalidKeyName => "invalid key name"
  | .missingTpmDevice => "missing TPM device"
  | .missingTool tool => s!"missing required tool: {tool}"
  | .biometricVerificationFailed stderr =>
      s!"biometric verification failed\n\n{stderr}"
  | .policyRejected => "Sepolia R1 account policy rejected"
  | .commandFailed cmd stderr =>
      s!"command failed: {cmd}\n\n{stderr}"

private def tpm2CreateReportText (report : CreateReport) : String :=
  "leanKohaku Sepolia TPM2 wallet creation\n\n\
   Requested wallet:\n\
     - chain: Sepolia (11155111)\n\
     - account: r1-smart dev account\n\
     - backend: local Linux TPM2\n\
     - curve: P-256/R1\n\
     - custody: local only; no online keystore\n\n\
   Result:\n\
     - status: " ++ tpm2CreateStatusText report.status ++ "\n\
     - key directory: " ++ report.keyDir.toString ++ "\n\
     - public key: " ++ report.publicKey.toString ++ "\n\
     - manifest: " ++ report.manifest.toString ++ "\n\n\
   Security boundary:\n\
     - created through local tpm2-tools only\n\
     - new key creation requires local fprintd biometric verification\n\
     - no seed or raw private key is generated by Lean\n\
     - TPM private blob remains wrapped for the local TPM\n\
     - biometric verification is a local gate, not yet a TPM policy session\n"

private def signStatusText : SignStatus → String
  | .signed => "signed"
  | .invalidKeyName => "invalid key name"
  | .invalidDigest => "invalid digest: expected 32-byte hex"
  | .missingKey => "missing key"
  | .missingTpmDevice => "missing TPM device"
  | .missingTool tool => s!"missing required tool: {tool}"
  | .biometricVerificationFailed stderr =>
      s!"biometric verification failed\n\n{stderr}"
  | .commandFailed cmd stderr =>
      s!"command failed: {cmd}\n\n{stderr}"

private def tpm2SignReportText (report : SignReport) : String :=
  let sigLine :=
    match report.signatureHex with
    | none => ""
    | some sig => "     - signature hex: " ++ sig ++ "\n"
  "leanKohaku Sepolia TPM2 signing\n\n\
   Requested signer:\n\
     - chain: Sepolia (11155111)\n\
     - key name: " ++ report.keyName ++ "\n\
     - backend: local Linux TPM2\n\n\
   Result:\n\
     - status: " ++ signStatusText report.status ++ "\n\
     - key directory: " ++ report.keyDir.toString ++ "\n\
     - digest file: " ++ report.digest.toString ++ "\n\
     - signature file: " ++ report.signature.toString ++ "\n" ++ sigLine ++
  "\n\
   Security boundary:\n\
     - signing requires local fprintd biometric verification\n\
     - digest and signature stay under the local .leankohaku state directory\n\
     - TPM private blob remains wrapped for the local TPM\n"

private def formatKeyList : List String → String
  | [] => "No local Sepolia TPM2 keys found.\n"
  | names =>
      "Local Sepolia TPM2 keys:\n" ++
        String.join (names.map (fun name => "- " ++ name ++ "\n"))

private def runScript (args : Array String) (env : Array (String × Option String) := #[]) :
    IO (UInt32 × String) := do
  try
    let out ← IO.Process.output
      { cmd := "./script/r1_sepolia.sh",
        args := args,
        env := env }
    pure (out.exitCode, out.stdout ++ out.stderr)
  catch e =>
    pure (1, e.toString ++ "\n")

private def paramName (params : Json) : Except RpcError String :=
  match params with
  | .obj _ =>
      match getField "name" params >>= asString with
      | some name => .ok name
      | none => .error invalidParams
  | .arr values =>
      match values.toList with
      | first :: _ =>
          match asString first with
          | some name => .ok name
          | none => .error invalidParams
      | [] => .error invalidParams
  | _ => .error invalidParams

private def paramString (params : Json) (key : String) : Except RpcError String :=
  match getField key params >>= asString with
  | some value => .ok value
  | none => .error invalidParams

private def paramStringD (params : Json) (key default : String) : String :=
  match getField key params >>= asString with
  | some value => value
  | none => default

private def paramNatD (params : Json) (key : String) (default : Nat) : Nat :=
  match getField key params >>= asNat with
  | some value => value
  | none => default

private def mnemonicFromPhrase (phrase : String) : LeanKohaku.Wallet.Mnemonic.Mnemonic :=
  { words := phrase.splitOn " " |>.filter (fun word => word != "") }

private def expectExcept {α : Type} : Except String α → IO α
  | .ok value => pure value
  | .error err => throw <| IO.userError err

private def deriveAddressFromSeed (seed : ByteArray) (path : String) :
    IO (Except String String) := do
  try
    discard <| expectExcept (LeanKohaku.Wallet.Bip44.validateEthereumPath path)
    let master ← expectExcept (← LeanKohaku.Wallet.HDKey.fromSeedIO seed)
    let child ← expectExcept (← LeanKohaku.Wallet.HDKey.derivePathIO master path)
    let pub ← expectExcept <| ← LeanKohaku.Crypto.Secp256k1Native.pubkeyIO
      (LeanKohaku.Crypto.Hex.encode (LeanKohaku.Wallet.HDKey.Nat.toFixedBytes 32 child.key))
      false
    let address ← expectExcept <| ← LeanKohaku.Wallet.Address.addressFromUncompressedPubkeyIO pub
    LeanKohaku.Wallet.Address.eip55Checksum address
  catch e =>
    pure (.error e.toString)

private def derivePrivateKeyFromSeed (seed : ByteArray) (path : String) :
    IO (Except String ByteArray) := do
  try
    discard <| expectExcept (LeanKohaku.Wallet.Bip44.validateEthereumPath path)
    let master ← expectExcept (← LeanKohaku.Wallet.HDKey.fromSeedIO seed)
    let child ← expectExcept (← LeanKohaku.Wallet.HDKey.derivePathIO master path)
    pure (.ok (LeanKohaku.Wallet.HDKey.Nat.toFixedBytes 32 child.key))
  catch e =>
    pure (.error e.toString)

private def unlockedSlot (state : LeanKohaku.Daemon.State.Shared) (name : String) :
    IO (Except RpcError LeanKohaku.Daemon.State.UnlockedSlot) := do
  match ← LeanKohaku.Daemon.State.getUnlocked? state name with
  | some slot => pure (.ok slot)
  | none => pure (.error { code := -32012, message := "EOA slot is locked" })

private def signatureJson (sig : LeanKohaku.Crypto.Secp256k1.Signature) : Json :=
  .obj #[
    ("r", .str (LeanKohaku.Crypto.Hex.encode (LeanKohaku.Wallet.HDKey.Nat.toFixedBytes 32 sig.r))),
    ("s", .str (LeanKohaku.Crypto.Hex.encode (LeanKohaku.Wallet.HDKey.Nat.toFixedBytes 32 sig.s))),
    ("v", .num (Int.ofNat sig.v.toNat))
  ]

private def bytesToNat (bytes : ByteArray) : Nat :=
  bytes.foldl (init := 0) (fun acc byte => acc * 256 + byte.toNat)

private def hexChar (n : Nat) : Char :=
  match n with
  | 0 => '0' | 1 => '1' | 2 => '2' | 3 => '3'
  | 4 => '4' | 5 => '5' | 6 => '6' | 7 => '7'
  | 8 => '8' | 9 => '9' | 10 => 'a' | 11 => 'b'
  | 12 => 'c' | 13 => 'd' | 14 => 'e' | _ => 'f'

private def hexDigit? (c : Char) : Option Nat :=
  if '0' ≤ c && c ≤ '9' then
    some (c.toNat - '0'.toNat)
  else if 'a' ≤ c && c ≤ 'f' then
    some (10 + c.toNat - 'a'.toNat)
  else if 'A' ≤ c && c ≤ 'F' then
    some (10 + c.toNat - 'A'.toNat)
  else
    none

private def stripHexPrefix (s : String) : String :=
  if s.startsWith "0x" || s.startsWith "0X" then
    (s.drop 2).toString
  else
    s

partial def natHexDigits : Nat → List Char → List Char
  | 0, acc => acc
  | n, acc => natHexDigits (n / 16) (hexChar (n % 16) :: acc)

private def natQuantityHex (n : Nat) : String :=
  match n with
  | 0 => "0x0"
  | _ => "0x" ++ String.ofList (natHexDigits n [])

private def parseHexQuantityDigits : List Char → Nat → Option Nat
  | [], acc => some acc
  | c :: cs, acc => do
      let d ← hexDigit? c
      parseHexQuantityDigits cs (acc * 16 + d)

private def parseHexQuantity (s : String) : Option Nat :=
  let raw := stripHexPrefix s
  if raw.isEmpty then
    none
  else
    parseHexQuantityDigits raw.toList 0

private def jsonHexNat (json : Json) : Except RpcError Nat :=
  match asString json with
  | none => .error invalidParams
  | some s =>
      match parseHexQuantity s with
      | none => .error invalidParams
      | some n => .ok n

private def jsonHexNatIO (json : Json) (what : String) : IO Nat := do
  match jsonHexNat json with
  | .ok n => pure n
  | .error _ => throw <| IO.userError s!"invalid hex quantity for {what}"

private def txNatField (tx : Json) (key : String) : Except RpcError Nat :=
  match getField key tx >>= asNat with
  | some value => .ok value
  | none => .error invalidParams

private def paramNat (params : Json) (key : String) : Except RpcError Nat :=
  match getField key params >>= asNat with
  | some value => .ok value
  | none => .error invalidParams

private def txBytesFieldD (tx : Json) (key : String) (default : ByteArray := ByteArray.empty) :
    Except RpcError ByteArray :=
  match getField key tx with
  | none => .ok default
  | some json =>
      match asBytes json with
      | some bytes => .ok bytes
      | none => .error invalidParams

private def txToField (tx : Json) : Except RpcError (Option LeanKohaku.Ethereum.Address.Address) :=
  match getField "to" tx with
  | none => .ok none
  | some .null => .ok none
  | some (.str s) =>
      match LeanKohaku.Ethereum.Address.fromHex s with
      | some address => .ok (some address)
      | none => .error invalidParams
  | some _ => .error invalidParams

private def erc20BalanceOfData (owner : LeanKohaku.Ethereum.Address.Address) : String :=
  "0x70a08231" ++ String.ofList (List.replicate 24 '0') ++ stripHexPrefix (LeanKohaku.Crypto.Hex.encode owner.bytes)

private def paramTxRequest (params : Json) : Except RpcError Json :=
  match getField "tx" params with
  | some (.obj fields) => .ok (.obj fields)
  | some _ => .error invalidParams
  | none => .error invalidParams

private def txFromJson (tx : Json) : Except RpcError LeanKohaku.Ethereum.Tx.TxEip1559 := do
  let chainId ← txNatField tx "chainId"
  let nonce ← txNatField tx "nonce"
  let maxPriorityFeePerGas ← txNatField tx "maxPriorityFeePerGas"
  let maxFeePerGas ← txNatField tx "maxFeePerGas"
  let gasLimit ← txNatField tx "gasLimit"
  let to ← txToField tx
  let value ← txNatField tx "value"
  let data ← txBytesFieldD tx "data"
  .ok {
    chainId := chainId,
    nonce := nonce,
    maxPriorityFeePerGas := maxPriorityFeePerGas,
    maxFeePerGas := maxFeePerGas,
    gasLimit := gasLimit,
    to := to,
    value := value,
    data := data,
    accessList := []
  }

private def paramTx (params : Json) : Except RpcError LeanKohaku.Ethereum.Tx.TxEip1559 :=
  match getField "tx" params with
  | some tx => txFromJson tx
  | none => txFromJson params

private def estimateTxJson (fromAddr to : String) (value : Nat) (data : ByteArray) : Json :=
  .obj #[
    ("from", .str fromAddr),
    ("to", .str to),
    ("value", .str (natQuantityHex value)),
    ("data", .str (LeanKohaku.Crypto.Hex.encode data))
  ]

private def sendResultJson (to value raw txHash : String)
    (nonce gasLimit maxPriorityFeePerGas maxFeePerGas : Nat)
    (sig : LeanKohaku.Crypto.Secp256k1.Signature) : Json :=
  .obj #[
    ("to", .str to),
    ("value", .str value),
    ("nonce", .str (natQuantityHex nonce)),
    ("gasLimit", .str (natQuantityHex gasLimit)),
    ("maxPriorityFeePerGas", .str (natQuantityHex maxPriorityFeePerGas)),
    ("maxFeePerGas", .str (natQuantityHex maxFeePerGas)),
    ("raw", .str raw),
    ("txHash", .str txHash),
    ("signature", signatureJson sig)
  ]

private def saveMnemonicSlot (params : Json) (generated : Option LeanKohaku.Wallet.Mnemonic.Mnemonic := none) :
    IO (Except RpcError (LeanKohaku.Wallet.EoaStore.Record × Option LeanKohaku.Wallet.Mnemonic.Mnemonic)) := do
  try
    let name ← expectExcept <| paramString params "name" |>.mapError (fun _ => "missing name")
    let passphrase ← expectExcept <| paramString params "passphrase" |>.mapError (fun _ => "missing passphrase")
    let derivationPath := paramStringD params "derivationPath" defaultDerivationPath
    let mnemonic ←
      match generated with
      | some m => pure m
      | none =>
          let phrase ← expectExcept <| paramString params "mnemonic" |>.mapError (fun _ => "missing mnemonic")
          pure (mnemonicFromPhrase phrase)
    let seed ← expectExcept <| ← LeanKohaku.Wallet.Mnemonic.mnemonicToSeedIO mnemonic ""
    let address ← expectExcept <| ← deriveAddressFromSeed seed derivationPath
    let record ← expectExcept <| ← LeanKohaku.Wallet.EoaStore.saveEncryptedSeed
      name passphrase seed derivationPath address
    pure (.ok (record, generated))
  catch e =>
    pure <| .error { invalidParams with data := some (.str e.toString) }

private def importResultJson (state : LeanKohaku.Daemon.State.Shared)
    (record : LeanKohaku.Wallet.EoaStore.Record)
    (mnemonic? : Option LeanKohaku.Wallet.Mnemonic.Mnemonic := none) : IO Json := do
  let base ← slotMetadataJson state record
  match base with
  | .obj fields =>
      match mnemonic? with
      | none => pure (.obj fields)
      | some m => pure (.obj (fields.push ("mnemonic", .arr (m.words.toArray.map Json.str))))
  | other => pure other

private def removeSocketFile (socketPath : String) : IO Unit := do
  try
    IO.FS.removeFile socketPath
  catch _ =>
    pure ()

private def exitSoon (socketPath : String) : IO Unit := do
  IO.sleep 50
  removeSocketFile socketPath
  IO.Process.exit 0

def methodHandler (cfg : Config) (state : LeanKohaku.Daemon.State.Shared)
    (req : Request) : IO (Except RpcError Json) := do
  match req.method with
  | "daemon.ping" =>
      let shuttingDown ← LeanKohaku.Daemon.State.isShuttingDown state
      pure <| .ok <| .obj #[
        ("ok", .bool true),
        ("version", .str LeanKohaku.version),
        ("uptime", .num 0),
        ("locked", .arr ((← LeanKohaku.Daemon.State.unlockedNames state).toArray.map Json.str)),
        ("chainId", .num (Int.ofNat cfg.chainId)),
        ("shuttingDown", .bool shuttingDown)
      ]
  | "daemon.version" =>
      pure <| .ok <| .obj #[
        ("version", .str LeanKohaku.version),
        ("rpcSchemaMajor", .num 1)
      ]
  | "daemon.shutdown" =>
      LeanKohaku.Daemon.State.requestShutdown state
      discard <| IO.asTask (exitSoon cfg.socketPath)
      pure <| .ok <| .obj #[("ok", .bool true)]
  | "tpm.createSepolia" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok keyName =>
          let report ← createSepoliaR1Key { keyName := keyName }
          pure <| .ok <| textResultJson (tpm2CreateReportText report) report.status.exitCode
  | "tpm.listSepolia" =>
      let names ← listSepoliaKeys
      pure <| .ok <| textResultJson (formatKeyList names) 0
  | "tpm.signSepolia" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok keyName =>
          match paramString req.params "digest" with
          | .error err => pure (.error err)
          | .ok digest =>
              let report ← signSepoliaDigest digest { keyName := keyName }
              pure <| .ok <| textResultJson (tpm2SignReportText report) report.status.exitCode
  | "r1.sendSepolia" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok keyName =>
          match paramString req.params "to", paramString req.params "amountWei" with
          | .ok to, .ok amountWei =>
              let (exitCode, text) ← runScript #["send", to, amountWei] #[("LEAN_KOHAKU_TPM_KEY", some keyName)]
              pure <| .ok <| textResultJson text exitCode
          | _, _ => pure (.error invalidParams)
  | "r1.sendEthSepolia" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok keyName =>
          match paramString req.params "to", paramString req.params "amountEth" with
          | .ok to, .ok amountEth =>
              let (exitCode, text) ← runScript #["send-eth", to, amountEth] #[("LEAN_KOHAKU_TPM_KEY", some keyName)]
              pure <| .ok <| textResultJson text exitCode
          | _, _ => pure (.error invalidParams)
  | "chain.balance" =>
      match paramString req.params "address" with
      | .error err => pure (.error err)
      | .ok address =>
          match LeanKohaku.Ethereum.Address.fromHex address with
          | none => pure (.error invalidParams)
          | some _ =>
              let block := paramStringD req.params "block" "latest"
              match ← LeanKohaku.RPC.Outbound.getBalance cfg.policy cfg.rpcEndpoint address block with
              | .ok balance =>
                  pure <| .ok <| .obj #[
                    ("address", .str address),
                    ("block", .str block),
                    ("balance", balance)
                  ]
              | .error err =>
                  pure <| .error { code := -32020, message := "chain RPC failed", data := some (.str err) }
  | "chain.nonce" =>
      match paramString req.params "address" with
      | .error err => pure (.error err)
      | .ok address =>
          match LeanKohaku.Ethereum.Address.fromHex address with
          | none => pure (.error invalidParams)
          | some _ =>
              let block := paramStringD req.params "block" "pending"
              match ← LeanKohaku.RPC.Outbound.getTransactionCount cfg.policy cfg.rpcEndpoint address block with
              | .ok nonce =>
                  pure <| .ok <| .obj #[
                    ("address", .str address),
                    ("block", .str block),
                    ("nonce", nonce)
                  ]
              | .error err =>
                  pure <| .error { code := -32020, message := "chain RPC failed", data := some (.str err) }
  | "chain.gasPrice" =>
      match ← LeanKohaku.RPC.Outbound.gasPrice cfg.policy cfg.rpcEndpoint with
      | .ok gasPrice =>
          pure <| .ok <| .obj #[("gasPrice", gasPrice)]
      | .error err =>
          pure <| .error { code := -32020, message := "chain RPC failed", data := some (.str err) }
  | "chain.maxPriorityFeePerGas" =>
      match ← LeanKohaku.RPC.Outbound.maxPriorityFeePerGas cfg.policy cfg.rpcEndpoint with
      | .ok maxPriorityFeePerGas =>
          pure <| .ok <| .obj #[("maxPriorityFeePerGas", maxPriorityFeePerGas)]
      | .error err =>
          pure <| .error { code := -32020, message := "chain RPC failed", data := some (.str err) }
  | "chain.estimateGas" =>
      match paramTxRequest req.params with
      | .error err => pure (.error err)
      | .ok tx =>
          let block := paramStringD req.params "block" "latest"
          match ← LeanKohaku.RPC.Outbound.estimateGas cfg.policy cfg.rpcEndpoint tx block with
          | .ok gas =>
              pure <| .ok <| .obj #[
                ("tx", tx),
                ("block", .str block),
                ("gas", gas)
              ]
          | .error err =>
              pure <| .error { code := -32020, message := "chain RPC failed", data := some (.str err) }
  | "chain.tokenBalance" =>
      match paramString req.params "token", paramString req.params "owner" with
      | .ok token, .ok owner =>
          match LeanKohaku.Ethereum.Address.fromHex token, LeanKohaku.Ethereum.Address.fromHex owner with
          | some _, some ownerAddr =>
              let block := paramStringD req.params "block" "latest"
              let data := erc20BalanceOfData ownerAddr
              match ← LeanKohaku.RPC.Outbound.ethCall cfg.policy cfg.rpcEndpoint token data block with
              | .ok balance =>
                  pure <| .ok <| .obj #[
                    ("token", .str token),
                    ("owner", .str owner),
                    ("block", .str block),
                    ("balance", balance)
                  ]
              | .error err =>
                  pure <| .error { code := -32020, message := "chain RPC failed", data := some (.str err) }
          | _, _ => pure (.error invalidParams)
      | _, _ => pure (.error invalidParams)
  | "chain.sendRawTransaction" =>
      match paramString req.params "raw" with
      | .error err => pure (.error err)
      | .ok raw =>
          match LeanKohaku.Crypto.Hex.decode raw with
          | none => pure (.error invalidParams)
          | some bytes =>
              if bytes.isEmpty then
                pure (.error invalidParams)
              else
                match ← LeanKohaku.RPC.Outbound.sendRawTransaction cfg.policy cfg.rpcEndpoint raw with
                | .ok txHash =>
                    pure <| .ok <| .obj #[
                      ("raw", .str raw),
                      ("txHash", txHash)
                    ]
                | .error err =>
                    pure <| .error { code := -32020, message := "chain RPC failed", data := some (.str err) }
  | "eoa.list" =>
      let names ← LeanKohaku.Wallet.EoaStore.list
      let records ← names.foldlM
        (fun acc name => do
          match ← LeanKohaku.Wallet.EoaStore.load name with
          | .ok record => pure (acc.push (← slotMetadataJson state record))
          | .error _ => pure acc)
        #[]
      pure (.ok (.arr records))
  | "eoa.show" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok name =>
          match ← LeanKohaku.Wallet.EoaStore.load name with
          | .ok record => pure (.ok (← slotMetadataJson state record))
          | .error err =>
              pure <| .error { code := -32010, message := "EOA slot not found", data := some (.str err) }
  | "eoa.address" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok name =>
          match ← LeanKohaku.Wallet.EoaStore.load name with
          | .ok record => pure (.ok (.str record.address))
          | .error err =>
              pure <| .error { code := -32010, message := "EOA slot not found", data := some (.str err) }
  | "eoa.import" =>
      match ← saveMnemonicSlot req.params none with
      | .error err => pure (.error err)
      | .ok (record, _) => pure (.ok (← importResultJson state record))
  | "eoa.create" =>
      try
        let wordCount := paramNatD req.params "wordCount" 12
        let mnemonic ← LeanKohaku.Wallet.Entropy.generateMnemonic wordCount
        match ← saveMnemonicSlot req.params (some mnemonic) with
        | .error err => pure (.error err)
        | .ok (record, mnemonic?) => pure (.ok (← importResultJson state record mnemonic?))
      catch e =>
        pure <| .error { invalidParams with data := some (.str e.toString) }
  | "eoa.unlock" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok name =>
          match paramString req.params "passphrase" with
          | .error err => pure (.error err)
          | .ok passphrase =>
              match ← LeanKohaku.Wallet.EoaStore.load name with
              | .error err =>
                  pure <| .error { code := -32010, message := "EOA slot not found", data := some (.str err) }
              | .ok record =>
                  match ← LeanKohaku.Wallet.EoaStore.unlockSeedIO record passphrase with
                  | .error err =>
                      pure <| .error { code := -32011, message := "EOA unlock failed", data := some (.str err) }
                  | .ok seed =>
                      LeanKohaku.Daemon.State.unlock state {
                        name := record.name,
                        seed := seed,
                        address := record.address,
                        derivationPath := record.derivationPath,
                        unlockedAtMs := ← IO.monoMsNow,
                        ttlMs := 300000
                      }
                      pure (.ok (← slotMetadataJson state record))
  | "eoa.lock" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok name =>
          LeanKohaku.Daemon.State.lock state name
          pure (.ok (.obj #[("ok", .bool true)]))
  | "eoa.derive" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok name =>
          match ← unlockedSlot state name with
          | .error err => pure (.error err)
          | .ok slot =>
              let path := paramStringD req.params "path" slot.derivationPath
              match ← deriveAddressFromSeed slot.seed path with
              | .error err =>
                  pure <| .error { invalidParams with data := some (.str err) }
              | .ok address =>
                  pure <| .ok <| .obj #[
                    ("name", .str name),
                    ("path", .str path),
                    ("address", .str address)
                  ]
  | "eoa.signDigest" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok name =>
          match ← unlockedSlot state name with
          | .error err => pure (.error err)
          | .ok slot =>
              match getField "digest" req.params >>= asBytes with
              | none => pure (.error invalidParams)
              | some digest =>
                  let path := paramStringD req.params "path" slot.derivationPath
                  match ← derivePrivateKeyFromSeed slot.seed path with
                  | .error err =>
                      pure <| .error { invalidParams with data := some (.str err) }
                  | .ok privateKey =>
                      match ← LeanKohaku.Wallet.EOA.signDigestIO privateKey digest with
                      | .error err =>
                          pure <| .error { code := -32013, message := "EOA signing failed", data := some (.str err) }
                      | .ok sig => pure (.ok (signatureJson sig))
  | "eoa.signMessage" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok name =>
          match ← unlockedSlot state name with
          | .error err => pure (.error err)
          | .ok slot =>
              match getField "message" req.params >>= asBytes with
              | none => pure (.error invalidParams)
              | some msg =>
                  let path := paramStringD req.params "path" slot.derivationPath
                  match ← derivePrivateKeyFromSeed slot.seed path with
                  | .error err =>
                      pure <| .error { invalidParams with data := some (.str err) }
                  | .ok privateKey =>
                      match ← LeanKohaku.Wallet.EOA.signPersonalMessageIO msg privateKey with
                      | .error err =>
                          pure <| .error { code := -32013, message := "EOA signing failed", data := some (.str err) }
                      | .ok sig => pure (.ok (signatureJson sig))
  | "eoa.signTx" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok name =>
          match ← unlockedSlot state name with
          | .error err => pure (.error err)
          | .ok slot =>
              match paramTx req.params with
              | .error err => pure (.error err)
              | .ok tx =>
                  let path := paramStringD req.params "path" slot.derivationPath
                  match ← derivePrivateKeyFromSeed slot.seed path with
                  | .error err =>
                      pure <| .error { invalidParams with data := some (.str err) }
                  | .ok privateKey =>
                      match ← LeanKohaku.Wallet.EOA.signEip1559IO tx privateKey with
                      | .error err =>
                          pure <| .error { code := -32013, message := "EOA signing failed", data := some (.str err) }
                      | .ok signed =>
                          pure <| .ok <| .obj #[
                            ("raw", .str (LeanKohaku.Crypto.Hex.encode signed.encode)),
                            ("signature", signatureJson signed.sig)
                          ]
  | "eoa.send" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok name =>
          match ← unlockedSlot state name with
          | .error err => pure (.error err)
          | .ok slot =>
              match paramString req.params "to", paramNat req.params "value" with
              | .ok to, .ok value =>
                  match LeanKohaku.Ethereum.Address.fromHex to with
                  | none => pure (.error invalidParams)
                  | some toAddress =>
                      match txBytesFieldD req.params "data" with
                      | .error err => pure (.error err)
                      | .ok data =>
                          let path := paramStringD req.params "path" slot.derivationPath
                          match ← derivePrivateKeyFromSeed slot.seed path with
                          | .error err =>
                              pure <| .error { invalidParams with data := some (.str err) }
                          | .ok privateKey =>
                              try
                                let nonceJson ← expectExcept <| (← LeanKohaku.RPC.Outbound.getTransactionCount cfg.policy cfg.rpcEndpoint slot.address "pending")
                                let priorityJson ← expectExcept <| (← LeanKohaku.RPC.Outbound.maxPriorityFeePerGas cfg.policy cfg.rpcEndpoint)
                                let gasPriceJson ← expectExcept <| (← LeanKohaku.RPC.Outbound.gasPrice cfg.policy cfg.rpcEndpoint)
                                let nonce ← jsonHexNatIO nonceJson "nonce"
                                let maxPriorityFeePerGas ← jsonHexNatIO priorityJson "maxPriorityFeePerGas"
                                let gasPrice ← jsonHexNatIO gasPriceJson "gasPrice"
                                let maxFeePerGas := gasPrice + maxPriorityFeePerGas
                                let estimateRequest := estimateTxJson slot.address to value data
                                let gasJson ← expectExcept <| (← LeanKohaku.RPC.Outbound.estimateGas cfg.policy cfg.rpcEndpoint estimateRequest "latest")
                                let gasLimit ← jsonHexNatIO gasJson "gasLimit"
                                let tx : LeanKohaku.Ethereum.Tx.TxEip1559 := {
                                  chainId := cfg.chainId,
                                  nonce := nonce,
                                  maxPriorityFeePerGas := maxPriorityFeePerGas,
                                  maxFeePerGas := maxFeePerGas,
                                  gasLimit := gasLimit,
                                  to := some toAddress,
                                  value := value,
                                  data := data,
                                  accessList := []
                                }
                                match ← LeanKohaku.Wallet.EOA.signEip1559IO tx privateKey with
                                | .error err =>
                                    pure <| .error { code := -32013, message := "EOA signing failed", data := some (.str err) }
                                | .ok signed =>
                                    let raw := LeanKohaku.Crypto.Hex.encode signed.encode
                                    match ← LeanKohaku.RPC.Outbound.sendRawTransaction cfg.policy cfg.rpcEndpoint raw with
                                    | .error err =>
                                        pure <| .error { code := -32020, message := "chain RPC failed", data := some (.str err) }
                                    | .ok txHashJson =>
                                        match txHashJson with
                                        | .str txHash =>
                                            pure <| .ok <| sendResultJson to (toString value) raw txHash
                                              nonce gasLimit maxPriorityFeePerGas maxFeePerGas signed.sig
                                        | _ =>
                                            pure <| .error { code := -32020, message := "chain RPC failed", data := some (.str "eth_sendRawTransaction returned non-string result") }
                              catch e =>
                                pure <| .error { code := -32020, message := "chain RPC failed", data := some (.str e.toString) }
              | _, _ => pure (.error invalidParams)
  | "eoa.delete" =>
      match paramName req.params with
      | .error err => pure (.error err)
      | .ok name =>
          match paramString req.params "passphrase" with
          | .error err => pure (.error err)
          | .ok passphrase =>
              match ← LeanKohaku.Wallet.EoaStore.load name with
              | .error err =>
                  pure <| .error { code := -32010, message := "EOA slot not found", data := some (.str err) }
              | .ok record =>
                  match ← LeanKohaku.Wallet.EoaStore.unlockSeedIO record passphrase with
                  | .error err =>
                      pure <| .error { code := -32011, message := "EOA unlock failed", data := some (.str err) }
                  | .ok _ =>
                      LeanKohaku.Daemon.State.lock state name
                      LeanKohaku.Wallet.EoaStore.delete name
                      pure (.ok (.obj #[("ok", .bool true)]))
  | "shielded.ping" =>
      let resp ← LeanKohaku.Privacy.Bridge.ping
      pure <| .ok <| LeanKohaku.Privacy.Bridge.responseToJson resp
  | _ =>
      pure (.error methodNotFound)

private def ensureParentDir (socketPath : String) : IO Unit := do
  let path : System.FilePath := socketPath
  match path.parent with
  | some parent => IO.FS.createDirAll parent
  | none => pure ()

private def decodeRequestBytes (bytes : ByteArray) : Except String String :=
  match String.fromUTF8? bytes with
  | some s => .ok s.trimAscii.toString
  | none => .error "request was not valid UTF-8"

def handleConn (cfg : Config) (state : LeanKohaku.Daemon.State.Shared)
    (conn : LeanKohaku.Daemon.Uds.Conn) : IO Unit := do
  try
    let started ← IO.monoMsNow
    let sameUid ← LeanKohaku.Daemon.Uds.peerUidMatchesCurrent conn
    if !sameUid then
      let response := compact <| errorResponse .null
        { code := -32001, message := "peer uid rejected" }
      discard <| LeanKohaku.Daemon.Uds.write conn (response ++ "\n").toByteArray
      LeanKohaku.Daemon.Log.write .warn "<peer>" ((← IO.monoMsNow) - started) false
        (some "peer uid rejected")
    else
      let bytes ← LeanKohaku.Daemon.Uds.read conn
      match decodeRequestBytes bytes with
      | .error err =>
          let response := compact <| errorResponse .null
            { parseError with data := some (.str err) }
          discard <| LeanKohaku.Daemon.Uds.write conn (response ++ "\n").toByteArray
          LeanKohaku.Daemon.Log.write .warn "<parse>" ((← IO.monoMsNow) - started) false
            (some err)
      | .ok line =>
          let parsed := LeanKohaku.RPC.Server.parseRequest line
          let method :=
            match parsed with
            | .ok req => req.method
            | .error _ => "<parse>"
          let response ←
            match parsed with
            | .error err => pure (compact <| errorResponse .null err)
            | .ok req => do
                let json ← LeanKohaku.RPC.Server.dispatch (methodHandler cfg state) req
                pure (compact json)
          discard <| LeanKohaku.Daemon.Uds.write conn (response ++ "\n").toByteArray
          LeanKohaku.Daemon.Log.write .info method ((← IO.monoMsNow) - started) true
  finally
    LeanKohaku.Daemon.Uds.close conn

partial def acceptLoop (cfg : Config) (state : LeanKohaku.Daemon.State.Shared)
    (listener : LeanKohaku.Daemon.Uds.Listener) : IO Unit := do
  let conn ← LeanKohaku.Daemon.Uds.accept listener
  discard <| IO.asTask (handleConn cfg state conn)
  if !(← LeanKohaku.Daemon.State.isShuttingDown state) then
    acceptLoop cfg state listener

def run (cfg : Config) : IO Unit := do
  ensureParentDir cfg.socketPath
  let listener ← LeanKohaku.Daemon.Uds.bind cfg.socketPath
  let state ← LeanKohaku.Daemon.State.new
  IO.eprintln s!"leankohaku-daemon: listening on {cfg.socketPath}"
  try
    acceptLoop cfg state listener
  finally
    LeanKohaku.Daemon.Uds.closeListener listener
    removeSocketFile cfg.socketPath

end LeanKohaku.Daemon.Server
